repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # On Windows, git will convert all CRLF to LF,
    # but only after all hooks are done executing.
    # yamllint will fail before git has a chance to convert line endings,
    # so it must be explicitly done before yamllint
    -   id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'LF' character
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
    -   id: yamllint
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.56.0
    hooks:
    -   id: cfn-python-lint
        files: .*/.*\.(json|yml|yaml)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: remove-tabs
