language: python
python: 3.6
cache: pip
install:
  - pip install taskcat==0.8.50
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install pre-commit
stages:
  - name: validate
  - name: test
    if: branch = master AND type = push
  - name: deploy
    if: (tag =~ ^v) OR (branch = master AND type = push)
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: test
      script:
        - taskcat -c ci/taskcat-all.yaml --tag owner=taskcat
        - |
          if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
          then
            echo Validation FAILED!
            exit 1
          else
            echo Validation Passed!
            exit 0
          fi
    - stage: deploy
      script:
        - ./deploy-templates.sh || travis_terminate 1
